### ISSUE TITLE
Edit cable design

### ISSUE THREAD

**Issue by PhysicsUofRAUI** [PhysicsUofRAUI/binTempSensor#22]
Need to place filter capcitors most likely and perhaps change assembly methods. 

Use this method to find the right design (at the start)
1. One sensor at the end with of a 30 m wire with the capacitor near it. 
- if it does not work put a capacitor near the arduino too
- if that does not work remove the capacitor close to the sensor.
2. Add the other two sensors incrementally (change up capacitor positions somewhat logically).
3. Once it is working create a circuit diagram.

**Comment by khanafin** [comment]
Interesting Project...  I have developed a similar system for collecting temps underwater in lakes.  I use an ESP32 to send the data from TI tmp-107 sensors to a server via wifi or cellular 2G/3G/LTE.  I have 15-20 sensors monitoring the thermocline 150m offshore.  Sample data:
![image](https://user-images.githubusercontent.com/4839298/112244324-80f2b380-8c25-11eb-811f-20b8a1134628.png)
Let me know if you are interested in talking.  
Karl Hanafin
karl@hanafins.com

**Comment by PhysicsUofRAUI** [comment]
Using the DS18B20 sensors for the most part now so this is not needed anymore
